In [2]:
!pip install pyswarm

  Created wheel for pyswarm: filename=pyswarm-0.6-py3-none-any.whl size=4479 sha256=a447fac1361968800713fbeebe8026ba60935c4f57a1fb727860f17d4ba83f34
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\ff\d2\b7\80118e5698de2bd0b8d1b3397abf7fdfc45c15ffc454b52145
Successfully built pyswarm


In this code, we first define the CNN model architecture, the loss function, and the accuracy metric. Then, we define the PSO optimizer function, which takes the CNN model parameters and the dataset as inputs and returns the negative of the validation accuracy (since PSO is a minimization algorithm).

Next, we define the bounds for the CNN parameters and load the CIFAR-10 dataset. Finally, we define the PSO algorithm parameters, such as the number of particles and maximum iterations, and run the PSO algorithm using the pso() function from the pyswarm library. The pso() function takes as

In [1]:
import numpy as np
import tensorflow as tf
from pyswarm import pso

# Define the CNN model architecture
def create_model(input_shape, num_classes, filters=32, kernel_size=(3,3), pool_size=(2,2)):
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(filters, kernel_size, activation='relu', input_shape=input_shape),
        tf.keras.layers.MaxPooling2D(pool_size=pool_size),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Define the loss function and the accuracy metric
def loss_function(y_true, y_pred):
    loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
    return loss

def accuracy_metric(y_true, y_pred):
    correct_predictions = tf.equal(tf.argmax(y_true, axis=1), tf.argmax(y_pred, axis=1))
    accuracy = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
    return accuracy

# Define the PSO optimization function
def pso_optimizer(cnn_params, X_train, y_train, X_val, y_val):
    print(cnn_params)
    input_shape = X_train.shape[1:]
    num_classes = y_train.shape[1]
    model = create_model(input_shape, num_classes, filters=int(cnn_params[0]),
                         kernel_size=(int(cnn_params[1]), int(cnn_params[2])), 
                         pool_size=(int(cnn_params[3]), int(cnn_params[4])))
    model.compile(optimizer=tf.keras.optimizers.Adam(), loss=loss_function, metrics=[accuracy_metric])
    model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=32)
    _, val_acc = model.evaluate(X_val, y_val, verbose=1)
    return -val_acc

# Define the bounds for the CNN parameters
# bounds = [(16, 128), (3, 7), (3, 7), (2, 4), (2, 4)]
lb = [16,3,3,2,2]
ub = [128,7,7,4,4]
# Load the dataset
(X_train, y_train), (X_val, y_val) = tf.keras.datasets.cifar10.load_data()
X_train = X_train.astype('float32') / 255.
X_val = X_val.astype('float32') / 255.
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_val = tf.keras.utils.to_categorical(y_val, 10)

# Define the PSO algorithm parameters
n_particles = 10
max_iter = 20

# Run the PSO algorithm to optimize the CNN model
# best_cost, best_params = pso(pso_optimizer, bounds, args=(X_train, y_train, X_val, y_val), swarmsize=n_particles, maxiter=max_iter)
best_cost, best_params = pso(pso_optimizer, lb,ub, args=(X_train, y_train, X_val, y_val), swarmsize=n_particles, maxiter=max_iter)

# Print the best CNN model's parameters and validation accuracy
print("Best CNN parameters: ", best_params)
print("Best validation accuracy: ", -best_cost)


[103.23350192   4.40664845   6.16729221   2.67368455   3.96048844]
Epoch 1/10
1563/1563 [==============================] - 6s 2ms/step - loss: 1.4833 - accuracy_metric: 0.4754 - val_loss: 1.3210 - val_accuracy_metric: 0.5316
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1921 - accuracy_metric: 0.5885 - val_loss: 1.1532 - val_accuracy_metric: 0.5933
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0738 - accuracy_metric: 0.6301 - val_loss: 1.1354 - val_accuracy_metric: 0.6115
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9984 - accuracy_metric: 0.6569 - val_loss: 1.0821 - val_accuracy_metric: 0.6275
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9476 - accuracy_metric: 0.6735 - val_loss: 1.0640 - val_accuracy_metric: 0.6387
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9021 - accuracy_metric: 0.6893 - val_loss: 1.0718 - val_accuracy_

Epoch 5/10
1563/1563 [==============================] - 3s 2ms/step - loss: 1.1007 - accuracy_metric: 0.6177 - val_loss: 1.1560 - val_accuracy_metric: 0.6032
Epoch 6/10
1563/1563 [==============================] - 3s 2ms/step - loss: 1.0645 - accuracy_metric: 0.6331 - val_loss: 1.1811 - val_accuracy_metric: 0.5966
Epoch 7/10
1563/1563 [==============================] - 3s 2ms/step - loss: 1.0323 - accuracy_metric: 0.6421 - val_loss: 1.1450 - val_accuracy_metric: 0.6050
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0023 - accuracy_metric: 0.6539 - val_loss: 1.1454 - val_accuracy_metric: 0.6090
Epoch 9/10
1563/1563 [==============================] - 3s 2ms/step - loss: 0.9840 - accuracy_metric: 0.6605 - val_loss: 1.1601 - val_accuracy_metric: 0.6035
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.1214 - accuracy_metric: 0.6188
[128.           3.35232465   6.01458856   2.02513392   3.01335834]
Epoch 1/10
1563/1563 [=============

Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1757 - accuracy_metric: 0.5947 - val_loss: 1.1457 - val_accuracy_metric: 0.5991
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0465 - accuracy_metric: 0.6395 - val_loss: 1.1032 - val_accuracy_metric: 0.6225
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9547 - accuracy_metric: 0.6705 - val_loss: 1.1164 - val_accuracy_metric: 0.6134
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8820 - accuracy_metric: 0.6956 - val_loss: 1.0920 - val_accuracy_metric: 0.6251
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8217 - accuracy_metric: 0.7162 - val_loss: 1.1002 - val_accuracy_metric: 0.6351
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.7562 - accuracy_metric: 0.7381 - val_loss: 1.1328 - val_accuracy_metric: 0.6315
Epoch 8/10
1563/1563 [==============================

Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.1197 - accuracy_metric: 0.6210
[17.98852098  7.          6.38577001  2.74929527  3.53289803]
Epoch 1/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.5653 - accuracy_metric: 0.4469 - val_loss: 1.3682 - val_accuracy_metric: 0.5230
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.3103 - accuracy_metric: 0.5412 - val_loss: 1.2904 - val_accuracy_metric: 0.5511
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.2231 - accuracy_metric: 0.5752 - val_loss: 1.2463 - val_accuracy_metric: 0.5603
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1692 - accuracy_metric: 0.5953 - val_loss: 1.2152 - val_accuracy_metric: 0.5793
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1268 - accuracy_metric: 0.6120 - val_loss: 1.1445 - val_accuracy_metric: 0.6058
Epoch 6/10
1563/1563 [==================

Epoch 7/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8682 - accuracy_metric: 0.7006 - val_loss: 0.9760 - val_accuracy_metric: 0.6666
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8392 - accuracy_metric: 0.7122 - val_loss: 0.9854 - val_accuracy_metric: 0.6630
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8122 - accuracy_metric: 0.7219 - val_loss: 0.9907 - val_accuracy_metric: 0.6664
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0098 - accuracy_metric: 0.6576
[127.82043084   4.98936769   3.41937444   2.53135506   2.36489826]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4400 - accuracy_metric: 0.4927 - val_loss: 1.3509 - val_accuracy_metric: 0.5358
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1592 - accuracy_metric: 0.6002 - val_loss: 1.1360 - val_accuracy_metric: 0.6097
Epoch 3/10
1563/1563 [=============

Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0781 - accuracy_metric: 0.6279 - val_loss: 1.1498 - val_accuracy_metric: 0.6102
Epoch 5/10
1563/1563 [==============================] - 3s 2ms/step - loss: 1.0378 - accuracy_metric: 0.6423 - val_loss: 1.0884 - val_accuracy_metric: 0.6275
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0031 - accuracy_metric: 0.6540 - val_loss: 1.0647 - val_accuracy_metric: 0.6368
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9759 - accuracy_metric: 0.6661 - val_loss: 1.0681 - val_accuracy_metric: 0.6367
Epoch 8/10
1563/1563 [==============================] - 3s 2ms/step - loss: 0.9561 - accuracy_metric: 0.6727 - val_loss: 1.0654 - val_accuracy_metric: 0.6353
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9403 - accuracy_metric: 0.6761 - val_loss: 1.0772 - val_accuracy_metric: 0.6376
Epoch 10/10
313/313 [==============================]

Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4375 - accuracy_metric: 0.4960 - val_loss: 1.2620 - val_accuracy_metric: 0.5569
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1677 - accuracy_metric: 0.5976 - val_loss: 1.1442 - val_accuracy_metric: 0.6072
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0711 - accuracy_metric: 0.6328 - val_loss: 1.0601 - val_accuracy_metric: 0.6388
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0085 - accuracy_metric: 0.6552 - val_loss: 1.0447 - val_accuracy_metric: 0.6450
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9517 - accuracy_metric: 0.6744 - val_loss: 1.0371 - val_accuracy_metric: 0.6445
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9107 - accuracy_metric: 0.6877 - val_loss: 1.0169 - val_accuracy_metric: 0.6561
Epoch 7/10
1563/1563 [==============================

Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8863 - accuracy_metric: 0.6944 - val_loss: 1.0476 - val_accuracy_metric: 0.6472
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0382 - accuracy_metric: 0.6499
[70.05023071  4.31468806  6.20733467  3.38285755  3.61780845]
Epoch 1/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.4919 - accuracy_metric: 0.4734 - val_loss: 1.2764 - val_accuracy_metric: 0.5507
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1976 - accuracy_metric: 0.5847 - val_loss: 1.1462 - val_accuracy_metric: 0.6072
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0828 - accuracy_metric: 0.6234 - val_loss: 1.0686 - val_accuracy_metric: 0.6314
Epoch 4/10
1563/1563 [==============================] - 3s 2ms/step - loss: 1.0258 - accuracy_metric: 0.6447 - val_loss: 1.0661 - val_accuracy_metric: 0.6334
Epoch 5/10
1563/1563 [==================

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8767 - accuracy_metric: 0.7017 - val_loss: 1.0596 - val_accuracy_metric: 0.6390
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8305 - accuracy_metric: 0.7162 - val_loss: 1.0613 - val_accuracy_metric: 0.6430
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.7976 - accuracy_metric: 0.7262 - val_loss: 1.0433 - val_accuracy_metric: 0.6506
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.7573 - accuracy_metric: 0.7394 - val_loss: 1.0451 - val_accuracy_metric: 0.6547
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0605 - accuracy_metric: 0.6498
[120.38546879   4.01269659   3.85644953   4.           3.61510004]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4389 - accuracy_metric: 0.4931 - val_loss: 1.2782 - val_accuracy_metric: 0.5475
Epoch 2/10
1563/1563 [=============

Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0813 - accuracy_metric: 0.6231 - val_loss: 1.0844 - val_accuracy_metric: 0.6227
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0194 - accuracy_metric: 0.6475 - val_loss: 1.0560 - val_accuracy_metric: 0.6347
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9695 - accuracy_metric: 0.6658 - val_loss: 1.0405 - val_accuracy_metric: 0.6434
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9357 - accuracy_metric: 0.6792 - val_loss: 1.0271 - val_accuracy_metric: 0.6510
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9065 - accuracy_metric: 0.6888 - val_loss: 1.0453 - val_accuracy_metric: 0.6442
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8751 - accuracy_metric: 0.6988 - val_loss: 1.0261 - val_accuracy_metric: 0.6467
Epoch 9/10
1563/1563 [==============================

313/313 [==============================] - 1s 2ms/step - loss: 1.0319 - accuracy_metric: 0.6584
[114.29012282   4.03720662   4.19789038   4.           3.12965351]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4617 - accuracy_metric: 0.4857 - val_loss: 1.2657 - val_accuracy_metric: 0.5625
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1891 - accuracy_metric: 0.5869 - val_loss: 1.1498 - val_accuracy_metric: 0.6036
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0845 - accuracy_metric: 0.6265 - val_loss: 1.0723 - val_accuracy_metric: 0.6365
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0128 - accuracy_metric: 0.6524 - val_loss: 1.1110 - val_accuracy_metric: 0.6213
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9649 - accuracy_metric: 0.6688 - val_loss: 1.0400 - val_accuracy_metric: 0.6491
Epoch 6/10
1563/1563 [=========================

Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8615 - accuracy_metric: 0.7048 - val_loss: 1.0442 - val_accuracy_metric: 0.6412
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8339 - accuracy_metric: 0.7135 - val_loss: 1.0183 - val_accuracy_metric: 0.6595
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0037 - accuracy_metric: 0.6625
[128.           3.8267926    5.95610966   4.           3.73705936]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4486 - accuracy_metric: 0.4879 - val_loss: 1.2369 - val_accuracy_metric: 0.5725
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1781 - accuracy_metric: 0.5913 - val_loss: 1.1443 - val_accuracy_metric: 0.6074
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0749 - accuracy_metric: 0.6320 - val_loss: 1.0736 - val_accuracy_metric: 0.6283
Epoch 4/10
1563/1563 [=============

Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4430 - accuracy_metric: 0.4917 - val_loss: 1.3093 - val_accuracy_metric: 0.5376
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1678 - accuracy_metric: 0.5937 - val_loss: 1.1147 - val_accuracy_metric: 0.6180
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0660 - accuracy_metric: 0.6304 - val_loss: 1.0811 - val_accuracy_metric: 0.6237
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0011 - accuracy_metric: 0.6558 - val_loss: 1.0326 - val_accuracy_metric: 0.6433
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9518 - accuracy_metric: 0.6724 - val_loss: 1.0102 - val_accuracy_metric: 0.6518
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9206 - accuracy_metric: 0.6850 - val_loss: 0.9895 - val_accuracy_metric: 0.6651
Epoch 7/10
1563/1563 [==============================

Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8318 - accuracy_metric: 0.7152 - val_loss: 1.0013 - val_accuracy_metric: 0.6633
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0213 - accuracy_metric: 0.6549
[117.47477408   4.40727459   3.9836843    3.80008914   3.61354948]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4534 - accuracy_metric: 0.4893 - val_loss: 1.2711 - val_accuracy_metric: 0.5606
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1768 - accuracy_metric: 0.5934 - val_loss: 1.1425 - val_accuracy_metric: 0.6029
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0595 - accuracy_metric: 0.6380 - val_loss: 1.0747 - val_accuracy_metric: 0.6287
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9828 - accuracy_metric: 0.6610 - val_loss: 1.0372 - val_accuracy_metric: 0.6387
Epoch 5/10
1563/1563 [=============

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8885 - accuracy_metric: 0.6929 - val_loss: 1.0134 - val_accuracy_metric: 0.6506
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8498 - accuracy_metric: 0.7085 - val_loss: 1.0363 - val_accuracy_metric: 0.6490
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8100 - accuracy_metric: 0.7222 - val_loss: 0.9953 - val_accuracy_metric: 0.6585
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.7775 - accuracy_metric: 0.7316 - val_loss: 1.0165 - val_accuracy_metric: 0.6594
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0714 - accuracy_metric: 0.6414
[128.           3.99359992   3.90900753   4.           3.71703877]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4445 - accuracy_metric: 0.4949 - val_loss: 1.2783 - val_accuracy_metric: 0.5581
Epoch 2/10
1563/1563 [=============

Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0866 - accuracy_metric: 0.6259 - val_loss: 1.0588 - val_accuracy_metric: 0.6364
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0185 - accuracy_metric: 0.6497 - val_loss: 1.1094 - val_accuracy_metric: 0.6224
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9665 - accuracy_metric: 0.6670 - val_loss: 1.0225 - val_accuracy_metric: 0.6496
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9301 - accuracy_metric: 0.6796 - val_loss: 1.0347 - val_accuracy_metric: 0.6460
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8947 - accuracy_metric: 0.6934 - val_loss: 1.0331 - val_accuracy_metric: 0.6493
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8650 - accuracy_metric: 0.7029 - val_loss: 1.0261 - val_accuracy_metric: 0.6488
Epoch 9/10
1563/1563 [==============================

313/313 [==============================] - 1s 2ms/step - loss: 1.0028 - accuracy_metric: 0.6639
[122.18074698   4.12228611   3.93504707   3.59309949   3.47933282]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4358 - accuracy_metric: 0.4933 - val_loss: 1.2581 - val_accuracy_metric: 0.5595
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1614 - accuracy_metric: 0.5983 - val_loss: 1.1637 - val_accuracy_metric: 0.5973
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0675 - accuracy_metric: 0.6332 - val_loss: 1.0783 - val_accuracy_metric: 0.6313
Epoch 4/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9911 - accuracy_metric: 0.6585 - val_loss: 1.0445 - val_accuracy_metric: 0.6432
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9340 - accuracy_metric: 0.6803 - val_loss: 1.0547 - val_accuracy_metric: 0.6427
Epoch 6/10
1563/1563 [=========================

Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8564 - accuracy_metric: 0.7070 - val_loss: 1.0406 - val_accuracy_metric: 0.6472
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8300 - accuracy_metric: 0.7152 - val_loss: 1.0321 - val_accuracy_metric: 0.6542
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0226 - accuracy_metric: 0.6615
[123.53984581   4.03236414   4.21717329   4.           3.26360891]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4521 - accuracy_metric: 0.4868 - val_loss: 1.2427 - val_accuracy_metric: 0.5698
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1705 - accuracy_metric: 0.5963 - val_loss: 1.1399 - val_accuracy_metric: 0.6102
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0667 - accuracy_metric: 0.6340 - val_loss: 1.0673 - val_accuracy_metric: 0.6293
Epoch 4/10
1563/1563 [=============

Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9393 - accuracy_metric: 0.6775 - val_loss: 1.0255 - val_accuracy_metric: 0.6467
Epoch 6/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8993 - accuracy_metric: 0.6905 - val_loss: 0.9948 - val_accuracy_metric: 0.6598
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8672 - accuracy_metric: 0.7018 - val_loss: 1.0375 - val_accuracy_metric: 0.6522
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8313 - accuracy_metric: 0.7135 - val_loss: 0.9844 - val_accuracy_metric: 0.6597
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8062 - accuracy_metric: 0.7228 - val_loss: 0.9989 - val_accuracy_metric: 0.6648
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0197 - accuracy_metric: 0.6630
[121.35505262   4.05240755   4.23480752   3.41195581   3.4700787 ]
Epoch 1/10
1563/1563 [=============

Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8058 - accuracy_metric: 0.7228 - val_loss: 0.9726 - val_accuracy_metric: 0.6704
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0038 - accuracy_metric: 0.6642
[119.66499971   4.1523523    3.84051182   4.           3.43773101]
Epoch 1/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.4517 - accuracy_metric: 0.4892 - val_loss: 1.3112 - val_accuracy_metric: 0.5361
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1767 - accuracy_metric: 0.5968 - val_loss: 1.1420 - val_accuracy_metric: 0.6055
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0663 - accuracy_metric: 0.6321 - val_loss: 1.0776 - val_accuracy_metric: 0.6321
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9955 - accuracy_metric: 0.6568 - val_loss: 1.0274 - val_accuracy_metric: 0.6457
Epoch 5/10
1563/1563 [=============

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9205 - accuracy_metric: 0.6841 - val_loss: 1.0488 - val_accuracy_metric: 0.6421
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8921 - accuracy_metric: 0.6950 - val_loss: 1.0229 - val_accuracy_metric: 0.6578
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8626 - accuracy_metric: 0.7017 - val_loss: 1.0145 - val_accuracy_metric: 0.6637
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8300 - accuracy_metric: 0.7161 - val_loss: 0.9992 - val_accuracy_metric: 0.6672
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0317 - accuracy_metric: 0.6566
[119.93716878   3.98998911   3.67701104   4.           3.43146762]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4432 - accuracy_metric: 0.4924 - val_loss: 1.3003 - val_accuracy_metric: 0.5410
Epoch 2/10
1563/1563 [=============

Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0722 - accuracy_metric: 0.6290 - val_loss: 1.0775 - val_accuracy_metric: 0.6257
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0012 - accuracy_metric: 0.6557 - val_loss: 1.0196 - val_accuracy_metric: 0.6559
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9467 - accuracy_metric: 0.6748 - val_loss: 1.0219 - val_accuracy_metric: 0.6472
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9088 - accuracy_metric: 0.6881 - val_loss: 1.0859 - val_accuracy_metric: 0.6324
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8671 - accuracy_metric: 0.7023 - val_loss: 1.0274 - val_accuracy_metric: 0.6504
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8409 - accuracy_metric: 0.7110 - val_loss: 0.9866 - val_accuracy_metric: 0.6663
Epoch 9/10
1563/1563 [==============================

313/313 [==============================] - 1s 2ms/step - loss: 1.0086 - accuracy_metric: 0.6605
[121.1049144    4.08201779   4.20954958   4.           3.50430178]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4426 - accuracy_metric: 0.4916 - val_loss: 1.2637 - val_accuracy_metric: 0.5629
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1692 - accuracy_metric: 0.5937 - val_loss: 1.1916 - val_accuracy_metric: 0.5841
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0649 - accuracy_metric: 0.6335 - val_loss: 1.0667 - val_accuracy_metric: 0.6319
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9962 - accuracy_metric: 0.6576 - val_loss: 1.0484 - val_accuracy_metric: 0.6442
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9518 - accuracy_metric: 0.6717 - val_loss: 1.0460 - val_accuracy_metric: 0.6429
Epoch 6/10
1563/1563 [=========================

Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8293 - accuracy_metric: 0.7172 - val_loss: 0.9868 - val_accuracy_metric: 0.6678
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8023 - accuracy_metric: 0.7238 - val_loss: 1.0019 - val_accuracy_metric: 0.6623
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9888 - accuracy_metric: 0.6736
[119.82734639   4.07072914   3.72072327   4.           3.48307821]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4460 - accuracy_metric: 0.4911 - val_loss: 1.2687 - val_accuracy_metric: 0.5508
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1783 - accuracy_metric: 0.5936 - val_loss: 1.1277 - val_accuracy_metric: 0.6105
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0745 - accuracy_metric: 0.6303 - val_loss: 1.1307 - val_accuracy_metric: 0.6078
Epoch 4/10
1563/1563 [=============

Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9611 - accuracy_metric: 0.6687 - val_loss: 1.0763 - val_accuracy_metric: 0.6228
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9245 - accuracy_metric: 0.6848 - val_loss: 1.0380 - val_accuracy_metric: 0.6420
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8946 - accuracy_metric: 0.6940 - val_loss: 1.0284 - val_accuracy_metric: 0.6488
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8657 - accuracy_metric: 0.7037 - val_loss: 1.0223 - val_accuracy_metric: 0.6533
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8362 - accuracy_metric: 0.7126 - val_loss: 1.0189 - val_accuracy_metric: 0.6576
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0120 - accuracy_metric: 0.6545
[121.12542596   4.04888303   4.27342508   4.           3.52858893]
Epoch 1/10
1563/1563 [=============

Epoch 9/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8174 - accuracy_metric: 0.7174 - val_loss: 0.9763 - val_accuracy_metric: 0.6672
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9989 - accuracy_metric: 0.6605
[120.58776667   4.04455833   4.10174349   4.           3.46069639]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4535 - accuracy_metric: 0.4855 - val_loss: 1.2436 - val_accuracy_metric: 0.5699
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1852 - accuracy_metric: 0.5876 - val_loss: 1.1274 - val_accuracy_metric: 0.6157
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0700 - accuracy_metric: 0.6313 - val_loss: 1.0999 - val_accuracy_metric: 0.6202
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0046 - accuracy_metric: 0.6550 - val_loss: 1.0341 - val_accuracy_metric: 0.6463
Epoch 5/10
1563/1563 [=============

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9113 - accuracy_metric: 0.6878 - val_loss: 1.1098 - val_accuracy_metric: 0.6192
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8714 - accuracy_metric: 0.6997 - val_loss: 0.9943 - val_accuracy_metric: 0.6624
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8377 - accuracy_metric: 0.7129 - val_loss: 1.0168 - val_accuracy_metric: 0.6596
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8137 - accuracy_metric: 0.7211 - val_loss: 1.0047 - val_accuracy_metric: 0.6576
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9960 - accuracy_metric: 0.6636
[118.92220007   4.09138139   3.71910292   4.           3.39795085]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4463 - accuracy_metric: 0.4942 - val_loss: 1.2223 - val_accuracy_metric: 0.5731
Epoch 2/10
1563/1563 [=============

Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0681 - accuracy_metric: 0.6322 - val_loss: 1.0896 - val_accuracy_metric: 0.6242
Epoch 4/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0069 - accuracy_metric: 0.6530 - val_loss: 1.0726 - val_accuracy_metric: 0.6316
Epoch 5/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9491 - accuracy_metric: 0.6750 - val_loss: 1.0970 - val_accuracy_metric: 0.6206
Epoch 6/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9101 - accuracy_metric: 0.6893 - val_loss: 1.0125 - val_accuracy_metric: 0.6578
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8734 - accuracy_metric: 0.7008 - val_loss: 1.0083 - val_accuracy_metric: 0.6509
Epoch 8/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8445 - accuracy_metric: 0.7112 - val_loss: 1.0045 - val_accuracy_metric: 0.6556
Epoch 9/10
1563/1563 [==============================

313/313 [==============================] - 1s 2ms/step - loss: 1.0020 - accuracy_metric: 0.6603
[119.46936103   4.07574848   3.76030399   4.           3.42963842]
Epoch 1/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.4450 - accuracy_metric: 0.4937 - val_loss: 1.2423 - val_accuracy_metric: 0.5639
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1733 - accuracy_metric: 0.5935 - val_loss: 1.1410 - val_accuracy_metric: 0.6016
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0726 - accuracy_metric: 0.6282 - val_loss: 1.0685 - val_accuracy_metric: 0.6371
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0104 - accuracy_metric: 0.6507 - val_loss: 1.0391 - val_accuracy_metric: 0.6435
Epoch 5/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9528 - accuracy_metric: 0.6719 - val_loss: 1.0561 - val_accuracy_metric: 0.6361
Epoch 6/10
1563/1563 [=========================

Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8233 - accuracy_metric: 0.7172 - val_loss: 1.0249 - val_accuracy_metric: 0.6523
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.7920 - accuracy_metric: 0.7297 - val_loss: 1.0329 - val_accuracy_metric: 0.6546
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0114 - accuracy_metric: 0.6584
[120.50656358   4.04230971   3.69501399   4.           3.43032294]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4407 - accuracy_metric: 0.4937 - val_loss: 1.2502 - val_accuracy_metric: 0.5697
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1642 - accuracy_metric: 0.5973 - val_loss: 1.1118 - val_accuracy_metric: 0.6135
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0612 - accuracy_metric: 0.6348 - val_loss: 1.0590 - val_accuracy_metric: 0.6411
Epoch 4/10
1563/1563 [=============

Epoch 5/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9523 - accuracy_metric: 0.6732 - val_loss: 1.0522 - val_accuracy_metric: 0.6362
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9080 - accuracy_metric: 0.6894 - val_loss: 1.0312 - val_accuracy_metric: 0.6500
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8767 - accuracy_metric: 0.6993 - val_loss: 1.0514 - val_accuracy_metric: 0.6403
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8416 - accuracy_metric: 0.7109 - val_loss: 1.0158 - val_accuracy_metric: 0.6588
Epoch 9/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8089 - accuracy_metric: 0.7228 - val_loss: 0.9771 - val_accuracy_metric: 0.6687
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9947 - accuracy_metric: 0.6718
[119.66150171   4.06684468   3.72475358   4.           3.42443402]
Epoch 1/10
1563/1563 [=============

Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8135 - accuracy_metric: 0.7220 - val_loss: 0.9853 - val_accuracy_metric: 0.6673
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0550 - accuracy_metric: 0.6430
[120.6649353    4.04654912   3.79223829   4.           3.4007948 ]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4423 - accuracy_metric: 0.4920 - val_loss: 1.2309 - val_accuracy_metric: 0.5678
Epoch 2/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.1693 - accuracy_metric: 0.5974 - val_loss: 1.1680 - val_accuracy_metric: 0.5984
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0672 - accuracy_metric: 0.6336 - val_loss: 1.0772 - val_accuracy_metric: 0.6280
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9984 - accuracy_metric: 0.6604 - val_loss: 1.0357 - val_accuracy_metric: 0.6437
Epoch 5/10
1563/1563 [=============

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8992 - accuracy_metric: 0.6903 - val_loss: 1.0173 - val_accuracy_metric: 0.6562
Epoch 7/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8658 - accuracy_metric: 0.7019 - val_loss: 0.9964 - val_accuracy_metric: 0.6601
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8347 - accuracy_metric: 0.7124 - val_loss: 0.9755 - val_accuracy_metric: 0.6648
Epoch 9/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8073 - accuracy_metric: 0.7232 - val_loss: 1.0229 - val_accuracy_metric: 0.6546
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9737 - accuracy_metric: 0.6712
[119.9530776    4.03986592   3.71408642   3.90389058   3.43763631]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4390 - accuracy_metric: 0.4964 - val_loss: 1.2367 - val_accuracy_metric: 0.5639
Epoch 2/10
1563/1563 [=============

Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0611 - accuracy_metric: 0.6379 - val_loss: 1.0616 - val_accuracy_metric: 0.6358
Epoch 4/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9940 - accuracy_metric: 0.6575 - val_loss: 1.0314 - val_accuracy_metric: 0.6447
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9431 - accuracy_metric: 0.6771 - val_loss: 1.0326 - val_accuracy_metric: 0.6457
Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8982 - accuracy_metric: 0.6925 - val_loss: 1.0739 - val_accuracy_metric: 0.6275
Epoch 7/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8715 - accuracy_metric: 0.7001 - val_loss: 0.9698 - val_accuracy_metric: 0.6672
Epoch 8/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8362 - accuracy_metric: 0.7116 - val_loss: 1.0013 - val_accuracy_metric: 0.6650
Epoch 9/10
1563/1563 [==============================

313/313 [==============================] - 1s 2ms/step - loss: 1.0195 - accuracy_metric: 0.6569
[119.66187015   4.0783911    3.73219393   4.           3.42903624]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4494 - accuracy_metric: 0.4916 - val_loss: 1.2763 - val_accuracy_metric: 0.5664
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1725 - accuracy_metric: 0.5955 - val_loss: 1.1593 - val_accuracy_metric: 0.6060
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0721 - accuracy_metric: 0.6315 - val_loss: 1.0559 - val_accuracy_metric: 0.6334
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0077 - accuracy_metric: 0.6550 - val_loss: 1.0421 - val_accuracy_metric: 0.6446
Epoch 5/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9541 - accuracy_metric: 0.6741 - val_loss: 1.0169 - val_accuracy_metric: 0.6570
Epoch 6/10
1563/1563 [=========================

Epoch 8/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8322 - accuracy_metric: 0.7151 - val_loss: 0.9851 - val_accuracy_metric: 0.6646
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8091 - accuracy_metric: 0.7222 - val_loss: 0.9806 - val_accuracy_metric: 0.6740
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9779 - accuracy_metric: 0.6723
[119.6885404    4.04703854   3.70271898   4.           3.41792823]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4325 - accuracy_metric: 0.4984 - val_loss: 1.2435 - val_accuracy_metric: 0.5765
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1613 - accuracy_metric: 0.5999 - val_loss: 1.1513 - val_accuracy_metric: 0.6092
Epoch 3/10
1563/1563 [==============================] - 4s 2ms/step - loss: 1.0653 - accuracy_metric: 0.6333 - val_loss: 1.0769 - val_accuracy_metric: 0.6354
Epoch 4/10
1563/1563 [=============

Epoch 5/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9581 - accuracy_metric: 0.6707 - val_loss: 1.0126 - val_accuracy_metric: 0.6499
Epoch 6/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.9173 - accuracy_metric: 0.6866 - val_loss: 1.0539 - val_accuracy_metric: 0.6416
Epoch 7/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8738 - accuracy_metric: 0.6995 - val_loss: 1.0445 - val_accuracy_metric: 0.6512
Epoch 8/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8440 - accuracy_metric: 0.7118 - val_loss: 0.9727 - val_accuracy_metric: 0.6724
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8209 - accuracy_metric: 0.7166 - val_loss: 1.0161 - val_accuracy_metric: 0.6542
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9986 - accuracy_metric: 0.6633
[119.68877071   4.06141475   3.71590072   4.           3.42488133]
Epoch 1/10
1563/1563 [=============

Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8132 - accuracy_metric: 0.7208 - val_loss: 1.0137 - val_accuracy_metric: 0.6549
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 1.0090 - accuracy_metric: 0.6550
[120.04170034   4.02776936   3.75688063   4.           3.47554205]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4470 - accuracy_metric: 0.4912 - val_loss: 1.2385 - val_accuracy_metric: 0.5712
Epoch 2/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.1790 - accuracy_metric: 0.5933 - val_loss: 1.2419 - val_accuracy_metric: 0.5567
Epoch 3/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.0764 - accuracy_metric: 0.6281 - val_loss: 1.0958 - val_accuracy_metric: 0.6273
Epoch 4/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9999 - accuracy_metric: 0.6569 - val_loss: 1.0385 - val_accuracy_metric: 0.6431
Epoch 5/10
1563/1563 [=============

Epoch 6/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.9059 - accuracy_metric: 0.6881 - val_loss: 0.9940 - val_accuracy_metric: 0.6593
Epoch 7/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8703 - accuracy_metric: 0.7014 - val_loss: 1.0598 - val_accuracy_metric: 0.6410
Epoch 8/10
1563/1563 [==============================] - 4s 3ms/step - loss: 0.8387 - accuracy_metric: 0.7127 - val_loss: 0.9832 - val_accuracy_metric: 0.6596
Epoch 9/10
1563/1563 [==============================] - 4s 2ms/step - loss: 0.8079 - accuracy_metric: 0.7216 - val_loss: 1.0102 - val_accuracy_metric: 0.6588
Epoch 10/10
313/313 [==============================] - 1s 2ms/step - loss: 0.9749 - accuracy_metric: 0.6719
[119.89176324   4.05177847   3.71308356   4.           3.42236063]
Epoch 1/10
1563/1563 [==============================] - 4s 3ms/step - loss: 1.4440 - accuracy_metric: 0.4928 - val_loss: 1.2719 - val_accuracy_metric: 0.5508
Epoch 2/10
1563/1563 [=============